# Generated by Django 3.0.4 on 2020-05-13 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogcomment_blog', to='backend.blog', verbose_name='博客')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogcomment_parent', to='backend.blogComment', verbose_name='父级')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogcomment_reply', to=settings.AUTH_USER_MODEL, verbose_name='评论人')),
                ('reply_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogcomment_replyto', to=settings.AUTH_USER_MODEL, verbose_name='被评论人')),
            ],
            options={
                'verbose_name': '影评评论',
                'db_table': 'blogComment',
            },
        ),
    ]
